### ISSUE TITLE
Using OUTSET and OUTCLR

### ISSUE THREAD

**Issue by ElTangas** [MicrochipTech/Getting_Started_with_GPIO#1]
In this function:

```C
inline void LED_blink(uint32_t time_ms)
{
    for(uint8_t i = 0 ; i < NUMBER_OF_BLINKS ; i++)
    {
        PORTB.OUT |= PIN5_bm;
        _delay_ms(time_ms);
        PORTB.OUT &= ~PIN5_bm;
        _delay_ms(time_ms);
    }
}

```
Wouldn't it be better to use OUTSET and OUTCLR?

**Comment by alexmchp** [comment]
You are correct, using OUTSET AND OUTCLR is better. On the other hand, these examples are meant for beginner users so we use the standard approach.
